export const REQUEST_ALL_ANIMALS = "REQUEST_ALL_ANIMALS";
export const REQUEST_AVAILABLE_ANIMALS = "REQUEST_AVAILABLE_ANIMALS";
export const ADD_ANIMAL = "ADD_ANIMAL";
export const MARK_ANIMAL_ADOPTED = "MARK_ANIMAL_ADOPTED";
export const EDIT_ANIMAL = "EDIT_ANIMAL";
export const ANIMAL_ERROR = "ANIMAL_ERROR";
export const REQUEST_USER_DATA = "REQUEST_USER_DATA";
export const USER_ERROR = "USER_ERROR";